/*  File generated by: Map Ed v0.98.5 */



extern const u16 cavePalette[64];
extern const u16 caveTiles[16016];
extern const u16 caveMap2[6873];
extern const u16 caveMap1[19734];
extern const u16 caveMap0[65536];
